name: CI
on: [push]

jobs:
  miniconda:
    name: Setup and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v40
        with:
          files: |
            **.sh

      - uses: Klintrup/simple-shell-syntax-check@v2
        if: steps.changed-files.outputs.any_changed == 'true'
        with:
          files: ${{ steps.changed-files.outputs.all_changed_and_modified_files }}
          install_missing_shell: true
